odwrtw/polochon

config.example.yml, lib/config.go, lib/config_test.go, server/app.go, server/basic_auth.go, server/http.go
* Gorilla mux as a router
* negroni to handle middlewares
* render to render JSON responses
=> Better http router and basic auth config

lib/file.go, lib/modules.go, lib/movie.go, lib/show.go, lib/showepisode.go, lib/video.go, lib/videostore.go, server/http.go
Add a slug function
Add a way to download files via their slugs
=> Change the way movies and shows are marshalled

lib/movie.go, lib/showepisode.go, lib/video.go, lib/videostore.go, server/http.go
URLs:
* /movies/{slug}/download
* /shows/{slug}/download
=> Better URL for file downloads

.travis.yml
=> Revert "Enable armv6 and armv7 toolchain"

lib/calendar.go, lib/config.go, lib/detailer.go, lib/downloader.go, lib/fsnotifier.go, lib/guesser.go, lib/modules.go, lib/notifier.go, lib/showindex_test.go, lib/subtitler.go, lib/torrenter.go, lib/wishilister_test.go, lib/wishlister.go, modules/addicted/addicted.go, modules/canape/canape.go, modules/eztv/eztv.go, modules/fsnotify/fsnotify.go, modules/imdb/imdb.go, modules/imdb/imdb_test.go, modules/inotify/inotify.go, modules/openguessit/openguessit.go, modules/opensubtitles/opensubtitles.go, modules/opensubtitles/opensubtitles_test.go, modules/pushover/pushover.go, modules/tmdb/tmdb.go, modules/transmission/transmission.go, modules/tvdb/tvdb.go, modules/yifysubs/yifysubs.go, modules/yifysubs/yifysubs_test.go, modules/yts/yts.go
Let the module handle its own configurations
=> Use []byte for module configurations

config.example.yml, lib/movie.go, lib/showepisode.go, lib/torrent.go, lib/video.go, modules/kickass/kickass.go, modules/kickass/movies.go, modules/kickass/shows.go, server/downloader.go, server/modules_all.go
* Search movies and tv shows from kickass users
* GetDetails added to the downloader functions to be able to search from
title instead of IMDB ID only
=> Add kickass torrenter

lib/file.go, lib/file_test.go, lib/movie.go, lib/movie_test.go, lib/movieindex.go, lib/movieindex_test.go, lib/nfo.go, lib/show.go, lib/show_test.go, lib/showepisode.go, lib/showepisode_test.go, lib/showindex.go, lib/showindex_test.go, lib/video.go, lib/videostore.go, lib/videostore_test.go, server/app.go, server/config.go
=> Move Store function from Movie/Show to VideoStore

modules/openguessit/openguessit.go
While trying to get the release group
=> Fix case when guessit is nil

lib/modules.go, lib/movieindex_test.go, lib/showindex_test.go, modules/tmdb/tmdb.go, modules/tmdb/tmdb_test.go, modules/yifysubs/yifysubs_test.go
* gofmt -s on tests
* golint: fix invalid exported comment on fuc
* small refactoring for gocyclo
=> Fix most goreport card errors

.gitignore, server/app.go, server/http.go, server/polochon.go, token.exemple.yml, token/config.go, token/config_test.go, token/middleware.go, token/middleware_test.go, token/token.go, token/token_test.go
=> First Draft for token implementation

errors/error.go, lib/videostore.go, modules/inotify/inotify.go, server/modules_linux.go, token/config_test.go
* This fixes the "go test ./..." on os x
* small go vet / lint refactoring
=> Fix tests / builds on non linux systems

config.example.yml, lib/downloader.go, lib/file.go, lib/videostore.go, modules/transmission/transmission.go, server/app.go, server/cleaner.go, server/config.go, server/downloader.go
The cleaner deletes the torrent when the ratio is reached
The cleaner deletes all the non-needed files
=> Add a cleaner daemon

docker/run.sh
The [[ condition ]] is not valid in sh scripts
=> Fix docker script shebang

Makefile
=> Fix coveralls file coverage

README.md
=> Update README about builds

app/internal/app/app.go, app/internal/cleaner/cleaner.go, app/internal/downloader/downloader.go, app/internal/organizer/organizer.go, app/internal/safeguard/safeguard.go, app/internal/server/http.go, app/internal/subapp/base.go, app/internal/subapp/subapp.go
* Fix the downloader event channel
* Add panic recovery in the sub apps
=> Panic recovery

modules/opensubtitles/opensubtitles.go
=> Fix opensubtitle

app/internal/server/routes.go
=> Fix bad function for wishlist route

app/internal/app/app.go, app/internal/configuration/configuration.go, config.example.yml
* set the log level
* set the log output: stdout or file
=> Add logs configurations

config.example.yml, modules/canape/canape.go
Wishlists are now aquired via two different calls for shows and movies
in the new canape version
=> Update the canape module

app/organizer/organizer.go, app/server/movies.go, app/server/shows.go, config.example.yml, lib/configuration/configuration.go, lib/configuration/configuration_test.go, lib/file.go, lib/language.go, lib/language_test.go, lib/library/library_test.go, lib/movie.go, lib/show_episode.go, lib/subtitler.go, lib/video.go, modules/addicted/addicted.go, modules/opensubtitles/opensubtitles.go, modules/opensubtitles/opensubtitles_test.go, modules/yifysubs/yifysubs.go, modules/yifysubs/yifysubs_test.go
Update modules to be compatible
=> Allow multiple languages for subtitles

app/app/app.go, app/server/movies.go, app/server/routes.go, app/server/seasons.go, app/server/shows.go, app/server/subtitles.go, lib/configuration/configuration.go, lib/library/episodes.go, lib/library/functional_movies_test.go, lib/library/functional_shows_test.go, lib/library/functional_test.go, lib/library/index.go, lib/library/library.go, lib/library/library_test.go, lib/library/movies.go, lib/library/seasons.go, lib/library/shows.go, lib/media_index/movie_index.go, lib/media_index/movie_index_test.go, lib/media_index/show_index.go, lib/media_index/show_index_test.go, lib/media_index/utils.go, modules/mock/subtitler.go
Subtitles are now indexed
Rewrite parts of the index's structure to make this change
Rename some vars to be more coherent
=> Add subtitles in the index

app/server/routes.go, app/server/torrents.go, modules/transmission/transmission.go, token.exemple.yml
Make transmission module more robust while we're here
=> Add remove torrent feature

app/polochon_modules.go, app/server/routes.go, app/server/torrents.go, config.example.yml, lib/downloader.go, modules/aria2/aria2.go, modules/tmdb/tmdb.go, modules/transmission/transmission.go
* Add aria2
* Add a new id field in downloadable
This PR needs https://github.com/odwrtw/papi/pull/14 for canape to be compatible.
=> Add a new downloader: aria2

lib/library/episodes.go, lib/library/functional_test.go, lib/library/library.go, lib/library/movies.go
=> Only create a symlink if the downloader is enabled

app/server/shows.go, lib/library/functional_shows_test.go, lib/media_index/movie_index.go, lib/media_index/show_index.go
After for movies : 
```
{
"tt0208092": {
"subtitles": [
"fr_FR",
"en_US"
],
"title": "Snatch"
}
}
```
After for shows : 
```
{
"tt2707408": {
"title": "Narcos",
"seasons": {
"01": {
"01": {
"subtitles": [
"fr_FR",
"en_US"
]
}
}
}
}
}
```
Canape will need to be updated
=> Add title of shows and movies in the index

lib/library/functional_shows_test.go, lib/media_index/movie_index.go, lib/media_index/show_index.go
This gives a more consistent output in the API results.
=> Embed the video metadata in the index

app/app/app.go
=> Fix app's signals

modules/tvdb/tvdb.go
Add a searchByTvdb method
Add checks in order not to lose the ImdbID information
=> Improve tvdb module

go.mod, go.sum, modules/trakttv/detailer.go
TraktTV is now a ShowEpisode detailer
Get episodes details when Detailing a Show
Update trakttv library
=> Trakttv episodes

app/downloader/downloader.go, app/server/torrents.go, go.mod, go.sum, lib/downloader.go, modules/aria2/aria2.go, modules/mock/downloader.go, modules/transmission/labels.go, modules/transmission/labels_test.go, modules/transmission/transmission.go
It will help to later organise the files without guessing.
=> Add metadata in the torrents

lib/papi/movie.go, lib/papi/show.go
Let's not return anything but an error if nothing was found !
=> Fix papi return in nothing was found

lib/library/movies.go, lib/library/movies_test.go
=> Fix organising movies with slashes in the name

modules/eztv/eztv.go, modules/eztv/eztv_test.go
This allows to easily skip x265 or other torrents that we don't want
Signed-off-by: Lucas BEE <pouulet@gmail.com>
=> eztv: Add an "exclude_torrents_containing" option

modules/yifysubtitles/yifysubs.go
Use the levenshtein distance to find the subtitle to download.
=> Make yify subs more flexible

app/app/app.go, app/server/library.go, app/server/routes.go, cmd/polochonfs/movies.go, config.example.yml, lib/configuration/configuration.go, lib/configuration/file.go
Add a Library Refresh POST endpoint
Allow to disable organizer
=> Library Refresh

app/server/routes.go, app/server/subtitles.go, lib/language.go, lib/language_test.go, lib/media_index/subtitle.go, token.exemple.yml
Example:
```
cat subtitle.srt | curl -X POST \
--data-binary @- \
http://localhost:8088/shows/tt123456/seasons/02/episodes/01/subtitles/fr_FR/upload
```
=> Add routes to upload subtitles to polochon
